#ifndef CJSON_CONFIG_H
#define CJSON_CONFIG_H

#define CJSON_LEXER_TOKEN_BUFFER_SIZE       1024
#define CJSON_VERIFY_SCOPE_STACK_SIZE       1024
#define CJSON_PARSE_LEVEL_MAX_ELEMENTS      1024

#endif // CJSON_CONFIG_H